### ISSUE TITLE
Question, Can't figure out how to use ref

### ISSUE THREAD

**Issue by WillEhrendreich** [slaveOftime/Fun.Blazor#59]
Thank you so much for this really awesome library.

I'm using the FluentUI bindings, Server Side Rendering, trying to get an EditForm working. 

in regular blazor, it looks like this:     

<EditForm Model="@Content" @ref="_editForm" style="width: 100%">

but when I try to use what I think is the equivalent with this library, 

```fsharp
          EditForm'(){ 
            style' "width: 100%"
            Model this.Content

            ref (fun  ef -> 
              this._editForm <- new EditForm() 
              ())
          }


```
I get 

```log
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: EditForm requires either a Model parameter, or an EditContext parameter, please provide one of these.
      System.InvalidOperationException: EditForm requires either a Model parameter, or an EditContext parameter, please provide one of these.
         at Microsoft.AspNetCore.Components.Forms.EditForm.OnParametersSet()
         at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
                                                       LogValues<string>
"EditForm requires either a Model parameter, or an EditContext parameter, please provide one of these."
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Cannot access a disposed object.
      System.ObjectDisposedException: Cannot access a disposed object.
         at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
                              LogValues<string>

"Cannot access a disposed object."
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'Cfb42m_N1x83ir5bi_b4VSn9h9IblJNtEDz_XjCNcGw'.
      System.ObjectDisposedException: Cannot access a disposed object.
         at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
                                                       LogValues<CircuitId>
```

I've tried so many variations but I'm missing some insight, fundamentally about how this all works or something. 

can you point me in the right direction? why is my model not being created or getting disposed? it does it in csharp and blazor..  

https://github.com/slaveOftime/Fun.Blazor/blob/c0ee0d687fb3c8ff8b0e05a86abe82a086054fe5/Fun.Blazor/DslElementBuilder.fs#L33

**Comment by albertwoo** [comment]
@WillEhrendreich I think you can try change your code to:

```csharp
EditForm'(){ 
            ...
            // But remember to check the nullability for this._editForm
            ref (fun  ef ->  this._editForm <- ef)
}
```

**Comment by WillEhrendreich** [comment]
Ok, that suggestion makes that part of things work, thank you. 

I can open the edit dialog now.  

But now I'm getting this error when I try to do anything more with it:

```log


warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Unable to set property 'ChildContent' on object of type 'Microsoft.AspNetCore.Components.Forms.EditForm'. The error was: Unable to cast object of type 'Microsoft.AspNetCore.Components.RenderFragment' to type 'Microsoft.AspNetCore.Components.RenderFragment`1[Microsoft.AspNetCore.Components.Forms.EditContext]'.
      System.InvalidOperationException: Unable to set property 'ChildContent' on object of type 'Microsoft.AspNetCore.Components.Forms.EditForm'. The error was: Unable to cast object of type 'Microsoft.AspNetCore.Components.RenderFragment' to type 'Microsoft.AspNetCore.Components.RenderFragment`1[Microsoft.AspNetCore.Components.Forms.EditContext]'.
       ---> System.InvalidCastException: Unable to cast object of type 'Microsoft.AspNetCore.Components.RenderFragment' to type 'Microsoft.AspNetCore.Components.RenderFragment`1[Microsoft.AspNetCore.Components.Forms.EditContext]'.
         at Microsoft.AspNetCore.Components.Reflection.PropertySetter.CallPropertySetter[TTarget,TValue](Action`2 setter, Object target, Object value)
         at Microsoft.AspNetCore.Components.Reflection.PropertySetter.SetValue(Object target, Object value)
         at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|3_0(Object target, PropertySetter writer, String parameterName, Object value)
         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|3_0(Object target, PropertySetter writer, String parameterName, Object value)
         at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.SetProperties(ParameterView& parameters, Object target)
         at Microsoft.AspNetCore.Components.ParameterView.SetParameterProperties(Object target)
         at Microsoft.AspNetCore.Components.ComponentBase.SetParametersAsync(ParameterView parameters)
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)

```

This happens regardless of whether or not I use childContent [||] 

I can't use the dialog if it doesn't allow me to add things to display, obviously, so I'm wondering if there's something I'm doing wrong that's causing this to get disposed and I don't know it? 

here's what it looks like in fsharp for me:

```fsharp

//up towards the top of the file I have: 
    [<Parameter>] member val Content : ContentModel = new ContentModel() with get, set


// which is supposed to get it's model set when this component is created.

// a little further down I have: 
    member val _editForm = new EditForm() with get, set


// then in the render func:

          EditForm'(){ 
            Model (this.Content)
            style' "width: 100%"
            ref (fun  ef -> this._editForm <- ef)
            FluentLabel'(){
              Typo Typography.PaneHeader
              content $"{this.Content.CategoryName} - {this.Content.Description}"
              }
          }

```

**Comment by albertwoo** [comment]
@WillEhrendreich You can try below:

```fsharp
    /// I think ValueOption is better for perf than "new EditForm()"
    member val _editForm: ValueOption<EditForm> = ValueNone with get, set

    override _.Render() = 
        EditForm'() {
            ..
            // Below is the magic. I should limit or improve the EditForm component or any components which ChildContent only support RenderFragmnet<T> so user will not write it in invalid way.
            ChildContent(fun _ ->  html.fragment [|
                    FluentLabel'() {
                        Typo Typography.PaneHeader
                        $"{this.Content.CategoryName} - {this.Content.Description}"
                    }
            |])
            ref (fun ef -> this._editForm <- ValueSome ef)
        }
```

**Comment by WillEhrendreich** [comment]
for some reason, my this.Content keeps going null before it's able to be used by the editform. I'm passing it in when creating it, I thought. Have you gotten that to work?

**Comment by albertwoo** [comment]
@WillEhrendreich I do not know what is your complete code looks like, and how do you consume the component you created. Normally I only use component style when integreate with csharp or for some special use cases, functional style is easier than class component style.

Below is the whole demo for define a component and consume in fsharp (I build this demo based on this sample project: https://github.com/slaveOftime/Fun.Blazor.Samples/tree/main/samples/FunWasm.FluentUIDemo):

```fsharp
// Add below code to this file: https://github.com/slaveOftime/Fun.Blazor.Samples/blob/main/samples/FunWasm.FluentUIDemo/App.fs
type ContentMoDa() =
    member val CategoryName: string = "" with get, set
    member val Description: string = "" with get, set

type DemoComp() as this =
    inherit FunComponent()

    [<Parameter>]
    member val Content: ContentMoDa = ContentMoDa() with get, set

    [<Inject>]
    member val ToastService: IToastService = Unchecked.defaultof<IToastService> with get, set

    member val _editForm: ValueOption<EditForm> = ValueNone with get, set

    override _.Render() = EditForm'() {
        //...
        Model this.Content
        ChildContent(fun _ ->
            html.fragment [|
                FluentLabel'() {
                    Typo Typography.PaneHeader
                    $"{this.Content.CategoryName} - {this.Content.Description}"
                }
                FluentButton'() {
                    OnClick(fun _ -> this.ToastService.ShowInfo(this._editForm.Value.EditContext.Model.ToString()))
                    "Check form"
                }
            |]
        )
        ref (fun ef -> this._editForm <- ValueSome ef)
    }

let homePage =
    html.fragment [|
        SectionContent'() {
            SectionName "Title"
            "Home"
        }
        FluentLabel'() {
            Typo Typography.H1
            Color Color.Accent
            "Hi from FunBlazor"
        }
        html.blazor (ComponentAttrBuilder<DemoComp>().Add((fun x -> x.Content), ContentMoDa(CategoryName = "cat", Description = "foo")))
    |]
```

I got below result:
![image](https://github.com/slaveOftime/Fun.Blazor/assets/8017681/9ec2d2b3-24f7-4d90-9297-d75d295b39eb)
